= docker-flexget
:idprefix:
:idseparator: -
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
:repo: madwind/docker-flexget
:image: madwind/flexget

image:https://github.com/{repo}/actions/workflows/build-and-push.yaml/badge.svg[CI,link=https://github.com/{repo}/actions/workflows/build-and-push.yaml]
image:https://img.shields.io/docker/image-size/{image}?arch=arm64&logo=docker&logoColor=aqua&color=aqua[Docker Image Size,link=https://registry.hub.docker.com/r/{image}]
image:https://badgen.net/docker/pulls/{image}?icon=docker&color=pink[Downloads,link=https://registry.hub.docker.com/r/{image}]
image:https://img.shields.io/endpoint?url=https%3A%2F%2Fmogyo.ro%2Fquart-apis%2Ftgmembercount%3Fchat_id%3Dflexget_qbittorrent_mod[Telegram Group,link=https://t.me/flexget_qbittorrent_mod]

link:README.adoc[English]

docker-flexget 是用于运行 https://github.com/madwind/flexget_qbittorrent_mod[flexget_qbittorrent_mod] 的 Docker 映像。

== 使用

WARNING: 此 Docker 映像中未包含 flexget_qbittorrent_mod 插件。footnote:[如需使用此插件，将插件项目中的文件直接放置在 `<path for config files>/plugins` 中。]

两种运行方式择一：

=== docker run

[source,console,subs=attributes+]
$ docker run -d \
>   --name=<container name> \
>   -p 3539:3539 \
>   -v <path for data files>:/downloads \
>   -v <path for config files>:/config \
>   -e PUID=<UID for user> \
>   -e PGID=<GID for user> \
>   -e TZ=<timezone> \
>   -e FG_WEBUI_PASSWD=<password> \
>   -e FG_LOG_LEVEL=<log level>
>   {image}

=== docker compose

. 创建名为 `compose.yaml` 的文件并粘贴以下内容：
+
[source,yml,subs=attributes+]
services:
  flexget:
    image: {image}
    container_name: flexget
    environment:
      # 密码应保证复杂度
      FG_WEBUI_PASSWD: <password>
      # 日志级别
      FG_LOG_LEVEL: INFO
      TZ: Asia/Shanghai
      PUID: 1000
      PGID: 1000
    volumes:
      - <path for config files>:/config
      - <path for data files>:/downloads
    ports:
      - "3539:3539"
. 在 `compose.yaml` 文件同一目录下，运行：

 $ docker compose up

== 构建映像

=== 本地构建

要在本地构建 FlexGet Docker 映像，在本项目目录中运行：

 $ docker buildx f

=== 使用 GitHub Actions 构建

. https://github.com/{repo}/fork[复刻]存储库。
. 在 repository settings -> secrets and variables -> actions -> repository secrets，输入 `DOCKERHUB_USERNAME` 和 `DOCKERHUB_TOKEN`。
. 为你的存储库启用 Actions。
因你的存储库在复刻时包含工作流，GitHub 禁止其在复刻上运行。footnote:[Dependabot 同样默认不会在复刻中启用，在 repository insights -> dependency graph -> dependabot 中启用它。]
. git push 到 `main` 分支将自动构建并推送 Docker 映像。footnote:[README 和 LICENSE 文件在排除列表中，对它们的更改不会触发构建。]
